openapi: "3.0.0"
info:
  title: Яндекс Алиса API для Web-hook'а
  version: 1.0.1
paths:
  /webhook:
    post:
      description: URL для Web-hook'а
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlisaRequest'
      responses:
        '200':
          description: Сервис обработчика должен вернуть ответ за 3 секунды
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlisaResponse'
components:
  schemas:
    AlisaRequest:
      type: object
      properties:
        meta:
          type: object
          properties:
            locale:
              type: string
              description: Язык в POSIX-формате, максимум 64 символа.
              example: "ru-RU"
    AlisaResponse:
      type: string
      description: TBD